### ISSUE TITLE
Need for a HttpCLient factory 

### ISSUE THREAD

**Issue by shepherrrd** [apitoolkit/apitoolkit-dotnet#33]
### Is your feature request related to a problem? Please describe

using a http client factory DI for outgoing requests becomes easier , where I use an interface provided by the apitoolkit and make other requests from there rather than making a new instance to the httpclient which the lifetime might be shorter than the life time of the service used

### Describe the solution you'd like

Just A MiddleWare , which implements the httpclientfactory but then also reports the outgoing requests

### Are you able to assist to bring the feature to reality?

yes, I can

**Comment by dawkaka** [comment]
@shepherrrd thanks for pointing that out, it will be added in the next release.
